In [68]:
import pandas as pd
from sqlalchemy import create_engine

In [69]:
#df = pd.read_csv('employee.csv',header=0,index_col=0)
#print(df)
#engine = create_engine('mysql+pymysql://root:1234@localhost/okay',echo=True)
#conn = engine.connect()
#df.to_sql('employee',conn,if_exists='replace',index=True)

In [70]:
data = pd.DataFrame({
    'Name': ["Riya","Shreeram","Shree","Ram","Sadhna","Sushma"],
    'Age': [20,20,21,22,30,35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'Seattle', 'Houston']
})

data

       Name  Age         City
0      Riya   20     New York
1  Shreeram   20  Los Angeles
2     Shree   21      Chicago
3       Ram   22       Boston
4    Sadhna   30      Seattle
5    Sushma   35      Houston

In [71]:
data2 = pd.DataFrame([
    {"Name": "Alice", "Age": 20, "Marks": 85},
    {"Name": "Bob", "Age": 21, "Marks": 90},
    {"Name": "Charlie", "Age": 22, "Marks": 88}
])
data2

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     88

In [72]:
data.head(5)
data.tail(3)
data.shape[0]   # number of rows
data.shape[1]   # number of columns
data.dtypes     # data type of each column
'''print(data.columns)'''     # list column names # cleaner way is below
list(data.columns)

['Name', 'Age', 'City']

In [73]:
for col in data.columns:                 #This is useful when you want to loop through column names.
    print(col)

Name
Age
City

In [74]:
data["Name"]            # Single Column Selection
data[["Name","Age"]]        # Multi Column Selection

       Name  Age
0      Riya   20
1  Shreeram   20
2     Shree   21
3       Ram   22
4    Sadhna   30
5    Sushma   35

In [75]:
data[data['Age'] > 25]
data[data['City'] == 'Boston']

  Name  Age    City
3  Ram   22  Boston

Grouping Conditions (Very Important)

() is also used for logical conditions in pandas.

Because Python needs to know which condition to evaluate first.

In [76]:
data[(data['Age'] > 20) & (data['City'] == 'Chicago')]
data[(data['Age'] < 25 ) | (data['City'] == 'Chicago')]
data[data['City'] != 'Boston']

       Name  Age         City
0      Riya   20     New York
1  Shreeram   20  Los Angeles
2     Shree   21      Chicago
4    Sadhna   30      Seattle
5    Sushma   35      Houston

In [77]:
data[data['Name'].str.startswith('R')]
data[data['Name'].str.endswith('a')]
data[data['Name'].str.contains('ee')]

       Name  Age         City
1  Shreeram   20  Los Angeles
2     Shree   21      Chicago

In [ ]:
data['Name'] = data['Name'].str.upper()
print(data['Name'].str.upper())

       Name  Age         City
0      Riya   20     New York
1  Shreeram   20  Los Angeles
2     Shree   21      Chicago
3       Ram   22       Boston
4    Sadhna   30      Seattle
5    Sushma   35      Houston