In [185]:
import pandas as pd

# Two Main Data Structures
1. Series:
A single column of data

In [186]:
data = [1,2,3,4,5]
df = pd.Series(data, name='numbers', index=['a','b','c','d','e'])
print(df,end='\n\n')

s = df.to_frame()               # the index is preserved automatically.
print(s,end='\n\n')

df = pd.DataFrame(data)         # the index is generated automatically.
print(df)

a    1
b    2
c    3
d    4
e    5
Name: numbers, dtype: int64

   numbers
a        1
b        2
c        3
d        4
e        5

   0
0  1
1  2
2  3
3  4
4  5

In [187]:
df = pd.DataFrame(data, columns=['numbers'] , index = ['a','b','c','d','e'])        # the index is generated automatically. unless u specify it.
print(df)

   numbers
a        1
b        2
c        3
d        4
e        5

2. DataFrame:
A table (rows and columns)

In [188]:
data1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen'],
    'age': [25, 30, 35, 28, 22, 40, 27, 33],
    'height_cm': [165, 175, 180, 170, 160, 178, 168, 172],
    'weight_kg': [55, 78, 85, 72, 50, 90, 60, 68],
    'marks_math': [88, 92, 79, 85, 90, 75, 95, 82],
    'marks_science': [91, 89, 84, 88, 93, 80, 97, 86],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'Seattle', 'Houston', 'Denver', 'Miami']
})

data1.to_csv('students.csv', index=False, header=True)

In [189]:
df = data1.rename(columns={
    'name' : 'Name',
    'age'	: 'Age',
    'height_cm'	: 'Height',
    'weight_kg'	: 'Weight',
    'marks_math' :	'Maths',
    'marks_science' :  'Science',
    'city' : 'City'
})

df

      Name  Age  Height  Weight  Maths  Science         City
0    Alice   25     165      55     88       91     New York
1      Bob   30     175      78     92       89  Los Angeles
2  Charlie   35     180      85     79       84      Chicago
3    David   28     170      72     85       88       Boston
4      Eva   22     160      50     90       93      Seattle
5    Frank   40     178      90     75       80      Houston
6    Grace   27     168      60     95       97       Denver
7    Helen   33     172      68     82       86        Miami

In [190]:
df.to_csv('students.csv', index = False , header=True)

print(df)

      Name  Age  Height  Weight  Maths  Science         City
0    Alice   25     165      55     88       91     New York
1      Bob   30     175      78     92       89  Los Angeles
2  Charlie   35     180      85     79       84      Chicago
3    David   28     170      72     85       88       Boston
4      Eva   22     160      50     90       93      Seattle
5    Frank   40     178      90     75       80      Houston
6    Grace   27     168      60     95       97       Denver
7    Helen   33     172      68     82       86        Miami

📌drop() does not modify the original dataframe unless you:

Option 1 — Assign it back

Option 2 — Use inplace=True

In [191]:
df.drop('Science' ,axis=1, inplace=True)   # axis = 1 means column and inplace = True means it will change the original dataframe.
print(df)

      Name  Age  Height  Weight  Maths         City
0    Alice   25     165      55     88     New York
1      Bob   30     175      78     92  Los Angeles
2  Charlie   35     180      85     79      Chicago
3    David   28     170      72     85       Boston
4      Eva   22     160      50     90      Seattle
5    Frank   40     178      90     75      Houston
6    Grace   27     168      60     95       Denver
7    Helen   33     172      68     82        Miami

In [192]:
df.drop(columns=['Maths'], inplace=True)   # another way to drop a column. Better cleaner syntax.
df

      Name  Age  Height  Weight         City
0    Alice   25     165      55     New York
1      Bob   30     175      78  Los Angeles
2  Charlie   35     180      85      Chicago
3    David   28     170      72       Boston
4      Eva   22     160      50      Seattle
5    Frank   40     178      90      Houston
6    Grace   27     168      60       Denver
7    Helen   33     172      68        Miami

In [193]:
df['Maths'] = [88, 92, 79, 85, 90, 75, 95, 82]  # adding a new column to the dataframe.
df['Science'] = [91, 89, 84, 88, 93, 80, 97, 86]  # adding a new column to the dataframe.
print(df)

      Name  Age  Height  Weight         City  Maths  Science
0    Alice   25     165      55     New York     88       91
1      Bob   30     175      78  Los Angeles     92       89
2  Charlie   35     180      85      Chicago     79       84
3    David   28     170      72       Boston     85       88
4      Eva   22     160      50      Seattle     90       93
5    Frank   40     178      90      Houston     75       80
6    Grace   27     168      60       Denver     95       97
7    Helen   33     172      68        Miami     82       86

In [194]:
df.drop(index=[1,3], inplace = True)   # dropping rows by index.
print(df)

      Name  Age  Height  Weight      City  Maths  Science
0    Alice   25     165      55  New York     88       91
2  Charlie   35     180      85   Chicago     79       84
4      Eva   22     160      50   Seattle     90       93
5    Frank   40     178      90   Houston     75       80
6    Grace   27     168      60    Denver     95       97
7    Helen   33     172      68     Miami     82       86

In [195]:
df.index = range(1, len(df) +1)   # resetting the index after dropping rows.
print(df)

      Name  Age  Height  Weight      City  Maths  Science
1    Alice   25     165      55  New York     88       91
2  Charlie   35     180      85   Chicago     79       84
3      Eva   22     160      50   Seattle     90       93
4    Frank   40     178      90   Houston     75       80
5    Grace   27     168      60    Denver     95       97
6    Helen   33     172      68     Miami     82       86

In [196]:
col = df.pop('Science')
df.insert(4, 'Science', col)   # inserting the column back to its original position.
print(df)

      Name  Age  Height  Weight  Science      City  Maths
1    Alice   25     165      55       91  New York     88
2  Charlie   35     180      85       84   Chicago     79
3      Eva   22     160      50       93   Seattle     90
4    Frank   40     178      90       80   Houston     75
5    Grace   27     168      60       97    Denver     95
6    Helen   33     172      68       86     Miami     82

In [197]:
print(list(data1.columns))
print(list(df.columns))

['name', 'age', 'height_cm', 'weight_kg', 'marks_math', 'marks_science', 'city']
['Name', 'Age', 'Height', 'Weight', 'Science', 'City', 'Maths']

In [198]:
col = df.pop('City')
df['City'] = col # adding the column back to the end of the dataframe.
print(df)

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   25     165      55       91     88  New York
2  Charlie   35     180      85       84     79   Chicago
3      Eva   22     160      50       93     90   Seattle
4    Frank   40     178      90       80     75   Houston
5    Grace   27     168      60       97     95    Denver
6    Helen   33     172      68       86     82     Miami

Updating

In [199]:
df.loc[2,'Age'] = 40    #Assigns the value  (Updating single value)
df

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   25     165      55       91     88  New York
2  Charlie   40     180      85       84     79   Chicago
3      Eva   22     160      50       93     90   Seattle
4    Frank   40     178      90       80     75   Houston
5    Grace   27     168      60       97     95    Denver
6    Helen   33     172      68       86     82     Miami

In [200]:
df.loc[2,'Age'] == 30       #comparison operator 
df

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   25     165      55       91     88  New York
2  Charlie   40     180      85       84     79   Chicago
3      Eva   22     160      50       93     90   Seattle
4    Frank   40     178      90       80     75   Houston
5    Grace   27     168      60       97     95    Denver
6    Helen   33     172      68       86     82     Miami

In [201]:
df.loc[df['Name'] == 'Charlie' , 'Maths'] = 85 
df.loc[df['Name'] == 'Helen' , 'Weight'] = 62        #Updating Multiple Values
df

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   25     165      55       91     88  New York
2  Charlie   40     180      85       84     85   Chicago
3      Eva   22     160      50       93     90   Seattle
4    Frank   40     178      90       80     75   Houston
5    Grace   27     168      60       97     95    Denver
6    Helen   33     172      62       86     82     Miami

In [202]:
df['Age'] = df['Age'] + 1       #Updating an Entire Column
df

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   26     165      55       91     88  New York
2  Charlie   41     180      85       84     85   Chicago
3      Eva   23     160      50       93     90   Seattle
4    Frank   41     178      90       80     75   Houston
5    Grace   28     168      60       97     95    Denver
6    Helen   34     172      62       86     82     Miami

In [203]:
df.loc[df['Name'] == 'Frank' , 'Weight'] = 80       #Update using Condition
df

      Name  Age  Height  Weight  Science  Maths      City
1    Alice   26     165      55       91     88  New York
2  Charlie   41     180      85       84     85   Chicago
3      Eva   23     160      50       93     90   Seattle
4    Frank   41     178      80       80     75   Houston
5    Grace   28     168      60       97     95    Denver
6    Helen   34     172      62       86     82     Miami

In [204]:
df['Result'] = ''
df.loc[(df['Science'] >= 90) & (df['Maths'] >= 90) , 'Result'] = 'A+'
df

      Name  Age  Height  Weight  Science  Maths      City Result
1    Alice   26     165      55       91     88  New York
2  Charlie   41     180      85       84     85   Chicago
3      Eva   23     160      50       93     90   Seattle     A+
4    Frank   41     178      80       80     75   Houston
5    Grace   28     168      60       97     95    Denver     A+
6    Helen   34     172      62       86     82     Miami

In [205]:
#df.loc[(df['Science']) + (df['Maths']) >=90 , 'Result'] = 'A+'
#df.loc[((df['Science']) + (df['Maths']) >= 140) & ((df['Science']) + (df['Maths']) < 180) , 'Result'] = 'A'
#df

In [206]:
df['Total'] = df['Science'] + df['Maths']
df.loc[df['Total'] >= 180, 'Result'] = 'A+'
df.loc[(df['Total'] >= 140) & (df['Total'] < 180) , 'Result' ] = 'A'

In [207]:
df.loc[1, 'Age'] = 27
df.loc[4, 'Weight'] = 65
df

      Name  Age  Height  Weight  Science  Maths      City Result  Total
1    Alice   27     165      55       91     88  New York      A    179
2  Charlie   41     180      85       84     85   Chicago      A    169
3      Eva   23     160      50       93     90   Seattle     A+    183
4    Frank   41     178      65       80     75   Houston      A    155
5    Grace   28     168      60       97     95    Denver     A+    192
6    Helen   34     172      62       86     82     Miami      A    168

In [ ]:
df.loc[(df['Name'] == 'Grace') , 'City'] = 'Boston'
df

      Name  Age  Height  Weight  Science  Maths      City Result  Total
1    Alice   27     165      55       91     88  New York      A    179
2  Charlie   41     180      85       84     85   Chicago      A    169
3      Eva   23     160      50       93     90   Seattle     A+    183
4    Frank   41     178      65       80     75   Houston      A    155
5    Grace   28     168      60       97     95    Boston     A+    192
6    Helen   34     172      62       86     82     Miami      A    168

In [ ]:
df.loc[df['Name'] == 'Helen' ,'Maths' ] = 90
df

      Name  Age  Height  Weight  Science  Maths      City Result  Total
1    Alice   27     165      55       91     88  New York      A    179
2  Charlie   41     180      85       84     85   Chicago      A    169
3      Eva   23     160      50       93     90   Seattle     A+    183
4    Frank   41     178      65       80     75   Houston      A    155
5    Grace   28     168      60       97     95    Boston     A+    192
6    Helen   34     172      62       86     90     Miami      A    168

In [210]:
df.loc[df['Name'] == 'Eva' , 'Result'] = 'A'
df

      Name  Age  Height  Weight  Science  Maths      City Result  Total
1    Alice   27     165      55       91     88  New York      A    179
2  Charlie   41     180      85       84     85   Chicago      A    169
3      Eva   23     160      50       93     90   Seattle      A    183
4    Frank   41     178      65       80     75   Houston      A    155
5    Grace   28     168      60       97     95    Boston     A+    192
6    Helen   34     172      62       86     90     Miami      A    168